# User.create!(name: "Kyle's Good Store", email: "kyle@email.com", password: "password", password_confirmation: "password", role: "admin")
# User.create!(name: "John Doe", email: "johndoe@email.com", password: "password", password_confirmation: "password", role: "member")
# User.create!(name: "Person", email: "person@email.com", password: "password", password_confirmation: "password", role: "member")

Category.create!(name: "Guitar")
Category.create!(name: "Bass")
Category.create!(name: "Drums")
Category.create!(name: "Keyboards")
Category.create!(name: "Pedals")
Category.create!(name: "Studio Gear")
Category.create!(name: "Other")
